Vagrant.configure("2") do |config|
  config.vm.box = "bento/rockylinux-9"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
  config.vm.provision "shell", path: "provisioner.sh"
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  config.vbguest.auto_update = false
end
