log_format json escape=json
  '{'
    '"upstream_resolve_time": "$upstream_resolve_time",'
    '"upstream_response_time": "$upstream_response_time",'
    '"upstream_connect_time": "$upstream_connect_time",'
    '"upstream_header_time": "$upstream_header_time",'
    '"status": "$status"'
  '}';
