access_log /var/log/nginx/json.log json;

server {
  listen 8001;
  server_name no_resolver;

  # skip: curl -H "X-Proxy-Host: 127.0.0.1" localhost:8001
  # status: 200 OK
  # error: OK
  #
  # command: curl -H "X-Proxy-Host: ipinfo.io" localhost:8001
  # status: 502 Bad Gateway
  # error: "no resolver defined to resolve ipinfo.io"

  location / {
    proxy_pass http://$http_x_proxy_host/;
  }
}

server {
  listen 8002;
  server_name bad_resolver;

  # skip: curl -H "X-Proxy-Host: 127.0.0.1" localhost:8002
  # status: 200 OK
  # error: OK
  #
  # command: curl -H "X-Proxy-Host: ipinfo.io" localhost:8002
  # status: 502 Bad Gateway
  # error: "ipinfo.io could not be resolved (110: Operation timed out)"
  #
  # command: timeout 1 curl -H "X-Proxy-Host: ipinfo.io" localhost:8002
  # status: 499 Client Closed Request
  # error: client closed request while resolving ipinfo.io

  location / {
    resolver 198.51.100.1;
    resolver_timeout 3s; # default: 30s
    proxy_pass http://$http_x_proxy_host/;
  }
}

server {
  listen 8003;
  server_name good_resolver;

  # command: curl -H "X-Proxy-Host: ipinfo.io" localhost:8003
  # status: 200 OK
  # error: OK
  #
  # command: curl -H "X-Proxy-Host: 127.0.0.1:44444" localhost:8003
  # status: 502 Bad Gateway
  # error: "connect() failed (111: Connection refused) while connecting to upstream"
  #
  # command: curl -H "X-Proxy-Host: nxdomain.test" localhost:8003
  # status: 502 Bad Gateway
  # error: "nxdomain.test could not be resolved (3: Host not found)"
  #
  # command: curl -H "X-Proxy-Host: dnssec-failed.org" localhost:8003
  # status: 502 Bad Gateway
  # error: "dnssec-failed.org could not be resolved (2: Server failure)"
  #
  # command: curl -H "X-Proxy-Host: 198.51.100.1" localhost:8003
  # status: 504 Gateway Time-out
  # error: "upstream timed out (110: Connection timed out) while connecting to upstream"
  #
  # command: timeout 1 curl -H "X-Proxy-Host: 198.51.100.1" localhost:8003
  # status: 499 Client Closed Request
  # error: client closed request while connecting to upstream
  #
  # command: curl -H "X-Proxy-Host: ipinfo.io:443" localhost:8003
  # status: 502 Bad Gateway
  # error: "upstream prematurely closed connection while reading response header from upstream"
  #
  # command: curl -H "X-Proxy-Host: httpbin.org" -H "X-Proxy-Path: delay/5" localhost:8003
  # status: 504 Gateway Time-out
  # error: "upstream timed out (110: Connection timed out) while reading response header from upstream"
  #
  # command: timeout 1 curl -H "X-Proxy-Host: httpbin.org" -H "X-Proxy-Path: delay/5" localhost:8003
  # status: 499 Client Closed Request
  # error: client closed request while reading response header from upstream

  location / {
    resolver 8.8.8.8;
    proxy_connect_timeout 3s; # default: 60s
    proxy_read_timeout 3s; # default: 60s
    proxy_next_upstream off; # default: on
    proxy_pass http://$http_x_proxy_host/$http_x_proxy_path;
  }
}

server {
  listen 8004;
  server_name bad_proxy_bind;

  # command: curl -H "X-Proxy-Host: ipinfo.io" localhost:8004
  # status: 500 Internal Server Error
  # error: "bind(198.51.100.1) failed (99: Cannot assign requested address) while connecting to upstream"

  location / {
    resolver 8.8.8.8;
    proxy_bind 198.51.100.1;
    proxy_pass http://$http_x_proxy_host/;
  }
}

server {
  listen 8005;
  server_name director;
  add_header X-Accel-Redirect @goto always;
  add_header X-Proxy-Host "ipinfo.io" always;
  return 200;
}

server {
  listen 8006;
  server_name entry;

  # command: curl localhost:8006
  # status: 200 OK
  # error: OK

  location / {
    proxy_pass http://127.0.0.1:8005;
  }

  location @goto {
    resolver 8.8.8.8;
    set $goto_proxy_host $upstream_http_x_proxy_host;
    proxy_pass http://$goto_proxy_host/;
  }
}
